var data2 =
   {
       jobs:[

           {
               comment:'sgr',
               title:{
                   icons:[
                       {
                           context:false,
                           iconName:'em-computer'
                       },
                       {
                           context:false,
                           iconName:'em-minidisc'
                       },
                       {
                           context:false,
                           iconName:' em-closed_lock_with_key'
                       },
                       {
                           context:false,
                           iconName:'em-heavy_multiplication_x'
                       },
                       {
                           context:false,
                           iconName:'em-bookmark'
                       }
                   ]
               },
               description:{
                   subpoints:[
                       {
                           icons:[
                               {
                                   context:false,
                                   iconName:'em-1234'
                               },
                               {
                                   context:false,
                                   iconName:'em-heavy_division_sign'
                               },
                               {
                                   context:false,
                                   iconName:'bracket'
                               },
                               {
                                   context:false,
                                   iconName:'bracket-right'
                               },
                           ]
                       },
                       {
                           icons:[
                               {
                                   context:false,
                                   iconName:'em-art'
                               },
                               {
                                   context:false,
                                   iconName:'em-pencil'
                               },
                               {
                                   context:false,
                                   iconName:'em-earth_asia'
                               },

                           ]
                       },
                       {
                           icons:[
                               {
                                   context:false,
                                   iconName:'em-mailbox_with_mail'
                               },
                               {
                                   context:false,
                                   iconName:'em-minidisc'
                               },
                               // {
                               //     context:false,
                               //     iconName:'em-airplane'
                               // },
                               {
                                   context:false,
                                   iconName:'information_desk_person'
                               },

                           ]
                       }
                   ]
               },
               time:7
           },

           ,
           {
               comment:'foodservice',
               title:{
                   icons:[
                       {
                           context:false,
                           iconName:'em-hamburger'
                       },
                       {
                           context:false,
                           iconName:'em-fries'
                       },
                       {
                           context:true,
                           icons:[
                               {
                                   iconName:'em-boot'
                               },
                               {
                                   iconName:'em-white_circle'
                               }
                           ]
                       }
                   ]
               },
               description:{
                   subpoints:[
                       {
                           icons:[
                               {
                                   context:false,
                                   iconName:'em-bookmark'
                               },
                               {
                                   context:true,
                                   icons:[
                                       {
                                           iconName:'em-information_desk_person'
                                       },
                                       {
                                           iconName:'em-sweat_drops'
                                       }
                                   ]
                               }
                           ]
                       }
                   ]
               },
               time:10
           },
           {
               comment:'foodservice',
               title:{
                   icons:[
                       {
                           context:false,
                           iconName:'em-fried_shrimp'
                       },
                       {
                           context:false,
                           iconName:'em-hocho'
                       },
                       {
                           context:false,
                           iconName:'em-tropical_fish'
                       },
                       {
                           context:false,
                           iconName:'em-shower'
                       },
                       {
                           context:false,
                           iconName:'em-sweat_drops'
                       }
                   ]
               },
               description:{
                   subpoints:[
                       {
                           icons:[
                               {
                                   context:false,
                                   iconName:'em-information_desk_person'
                               },
                               {
                                   context:true,
                                   icons:[
                                       {
                                           iconName:'em-boot'
                                       },
                                       {
                                           iconName:'em-white_circle'
                                       }
                                   ]
                               }
                           ]
                       }
                   ]
               },
               time:15
           }
       ]
   }